name: JASPAR-profile-inference
channels:
  - bioconda
  - conda-forge
  - insilichem
  - defaults
dependencies:
  - biopython=1.73
  - blast=2.9.0
  - glmnet=2.1.1
  - hmmer=3.2.1
  - meme=5.0.5
  - numpy=1.16.4
  - pandas=0.25.1
  - prody=1.10.8
  - python=3.7.3
  - python-coreapi=2.3.3
  - scipy=1.3.1
  - scikit-learn=0.21.3
  - tqdm=4.35.0
